/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-south-1",
    "aws_cognito_identity_pool_id": "ap-south-1:200d22c8-febd-4693-8f75-9ebc637ff07e",
    "aws_cognito_region": "ap-south-1",
    "aws_user_pools_id": "ap-south-1_cYmEeBLBA",
    "aws_user_pools_web_client_id": "3reomtej2mmdmi0mr8ridqmlqb",
    "oauth": {}
};


export default awsmobile;
